<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>edi</string>
	</array>
	<key>name</key>
	<string>Edifact</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>comment</key>
			<string>punctuation.seperator.field.edi</string>
			<key>match</key>
			<string>([\+\:]+)</string>
			<key>name</key>
			<string>keyword.other.edi</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>punctuation.terminator.edi</string>
			<key>match</key>
			<string>\'\n</string>
			<key>name</key>
			<string>string.quoted.single.edi</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#repository</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#segments</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>segments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(^[A-Z0-9]{3})|\b(AGR|BGM|BY|CAV|CCI|CNT|DDE|DDK|DDQ|DP|DTM|ERC|FTX|GC|GRP|GRU|IDE|INP|IT|IV|LIN|LOC|MKS|MR|MS|NAD|PIA|PQ|PRC|REG|RFF|QTY|SE|SEQ|SO|STS|SU|TAX|UCI|UD|UNA|UNB|UNH|UNOC|UNS|UNT|UNZ)\b</string>
					<key>name</key>
					<string>keyword.control.edi</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(PAT|MED|DOS|EPI|AGB|EML|ACB)\b</string>
					<key>name</key>
					<string>keyword.other.edi</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(PRK|GPK|HPK|PRE)\b</string>
					<key>name</key>
					<string>constant.character.edi</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\?[\']</string>
					<key>name</key>
					<string>constant.character.escape.java</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.edi</string>
	<key>uuid</key>
	<string>0b3e7731-5990-4852-b076-07c5cceccb38</string>
</dict>
</plist>
